### ISSUE TITLE
Getting unable to parse errors

### ISSUE THREAD

**Issue by charlesverdad** [pyroscope-io/jfr-parser#4]
Thanks for your work in getting jfr ingest support for Pyroscope. 

I'm trying out that feature but I can't get the parser to work. 

```sh
cat myjfr.jfr | curl --data-binary @- -X POST 'localhost:4040/ingest?name=foo'
```

I get an error that's coming from the parser.

```
time="2022-03-29T04:32:27.239297" level=error msg="error happened while parsing request body" file=" server/controller.go:559" error="unable to parse JFR format: unable to parse chunk: unable to parse chunk metadata: unable to parse metadata event's string: Unsupported string type :4"
```

I have two different jfr files: one created by Java Flight Recorder (`from-jfr.jfr`), and one created by `libasyncprofiler` (`from-ap.jfr`) with the following flags: `event=itimer,lock,alloc,loop=60s`.

Here are the error messages:

### Attempting to parse Java Flight Recorder output

```sh
 ~/work/jfr-parser  main   6s 
15:33:33 ❯ go run . ~/from-jfr.jfr
2022/03/29 15:33:48 Unable to parse: unable to parse chunk: unable to parse chunk metadata: unable to parse metadata event's string: Unsupported string type :4
exit status 1
```

### Attempting to parse Async Profiler output

```sh
 ~/work/jfr-parser  main  
15:33:48 ❯ go run . ~/from-ap.jfr
2022/03/29 15:34:13 Unable to parse: unable to parse chunk: unable to parse checkpoint event: unable to parse constant type 31: unknown type profiler.types.LogLevel
exit status 1
```

Note this error  `unable to parse constant type 31: unknown type profiler.types.LogLevel` is different from the first one. I'm more interested in this async-profiler output.

**Comment by abeaumont** [comment]
Thanks for reporting the problems @charlesverdad!

Both problems are expected, as the JFR support is still partial. [Pending work](https://github.com/pyroscope-io/jfr-parser#pending-work) has a summary of the missing parts. In the cases you are reporting:
- The first problem is an unsupported string encoding, we currently don't support type 4.
- The second problem is due to unsupported types. We currently don't support some of the most recently introduced types by async-profiler and the lock-related event types, thus the error.

Fortunately, both are relatively simple to fix. Adding lock event support in Pyroscope requires some additional work, but we can add support for these types and encodings at the parsing level so that Pyroscope can at least ingest them fine.

Could you attach the generated JFRs? They would be pretty helpful to validate everything works fine.

**Comment by charlesverdad** [comment]
> Could you attach the generated JFRs? They would be pretty helpful to validate everything works fine.

@abeaumont Sure thing! Here you go: [jfr_archive.zip](https://github.com/pyroscope-io/jfr-parser/files/8385433/jfr_archive.zip)

In the archive is:
- **from-jfr.jfr** : output of Java Flight Recorder
- **from-jfr.json** :  parsed using JMC's `jfr print --json` tool
- **from-ap.jfr**: output of libasyncProfiler
- **from-ap.json** : parsed using JMC's `jfr print --json` tool

**Comment by charlesverdad** [comment]
Thanks @abeaumont . I checked out that branch and I can confirm that it works for the async-profiler output 😄 . I even tried it out with the Pyroscope server and it seemd to work without any problems.

**Comment by abeaumont** [comment]
With the latest improvements in the parser, both provided JFR files should be properly parsed now :)
